/*
 * SPDX-FileCopyrightText: 2026 Deutsche Telekom AG
 *
 * SPDX-License-Identifier: APACHE-2.0
 */

package de.telekom.usp

import de.telekom.usp.PathElement.Object
import de.telekom.usp.internal.ResolvedPathImpl

// All object of first and second order:
val Device: ResolvedPath = ResolvedPathImpl(Object("Device."))
val Services: ResolvedPath = ResolvedPathImpl(Device.first(), Object("Services."))
val DeviceInfo: ResolvedPath = ResolvedPathImpl(Device.first(), Object("DeviceInfo."))
val Time: ResolvedPath = ResolvedPathImpl(Device.first(), Object("Time."))
val UserInterface: ResolvedPath = ResolvedPathImpl(Device.first(), Object("UserInterface."))
val DSL: ResolvedPath = ResolvedPathImpl(Device.first(), Object("DSL."))
val FAST: ResolvedPath = ResolvedPathImpl(Device.first(), Object("FAST."))
val Optical: ResolvedPath = ResolvedPathImpl(Device.first(), Object("Optical."))
val Cellular: ResolvedPath = ResolvedPathImpl(Device.first(), Object("Cellular."))
val ATM: ResolvedPath = ResolvedPathImpl(Device.first(), Object("ATM."))
val DOCSIS: ResolvedPath = ResolvedPathImpl(Device.first(), Object("DOCSIS."))
val PTM: ResolvedPath = ResolvedPathImpl(Device.first(), Object("PTM."))
val Ethernet: ResolvedPath = ResolvedPathImpl(Device.first(), Object("Ethernet."))
val USB: ResolvedPath = ResolvedPathImpl(Device.first(), Object("USB."))
val HPNA: ResolvedPath = ResolvedPathImpl(Device.first(), Object("HPNA."))
val MoCA: ResolvedPath = ResolvedPathImpl(Device.first(), Object("MoCA."))
val Ghn: ResolvedPath = ResolvedPathImpl(Device.first(), Object("Ghn."))
val HomePlug: ResolvedPath = ResolvedPathImpl(Device.first(), Object("HomePlug."))
val UPA: ResolvedPath = ResolvedPathImpl(Device.first(), Object("UPA."))
val WiFi: ResolvedPath = ResolvedPathImpl(Device.first(), Object("WiFi."))
val ZigBee: ResolvedPath = ResolvedPathImpl(Device.first(), Object("ZigBee."))
val Bridging: ResolvedPath = ResolvedPathImpl(Device.first(), Object("Bridging."))
val PPP: ResolvedPath = ResolvedPathImpl(Device.first(), Object("PPP."))
val IP: ResolvedPath = ResolvedPathImpl(Device.first(), Object("IP."))
val LLDP: ResolvedPath = ResolvedPathImpl(Device.first(), Object("LLDP."))
val IPsec: ResolvedPath = ResolvedPathImpl(Device.first(), Object("IPsec."))
val GRE: ResolvedPath = ResolvedPathImpl(Device.first(), Object("GRE."))
val L2TPv3: ResolvedPath = ResolvedPathImpl(Device.first(), Object("L2TPv3."))
val VXLAN: ResolvedPath = ResolvedPathImpl(Device.first(), Object("VXLAN."))
val MAP: ResolvedPath = ResolvedPathImpl(Device.first(), Object("MAP."))
val CaptivePortal: ResolvedPath = ResolvedPathImpl(Device.first(), Object("CaptivePortal."))
val Routing: ResolvedPath = ResolvedPathImpl(Device.first(), Object("Routing."))
val NeighborDiscovery: ResolvedPath = ResolvedPathImpl(Device.first(), Object("NeighborDiscovery."))
val RouterAdvertisement: ResolvedPath =
    ResolvedPathImpl(Device.first(), Object("RouterAdvertisement."))
val IPv6rd: ResolvedPath = ResolvedPathImpl(Device.first(), Object("IPv6rd."))
val DSLite: ResolvedPath = ResolvedPathImpl(Device.first(), Object("DSLite."))
val QoS: ResolvedPath = ResolvedPathImpl(Device.first(), Object("QoS."))
val LANConfigSecurity: ResolvedPath = ResolvedPathImpl(Device.first(), Object("LANConfigSecurity."))
val Hosts: ResolvedPath = ResolvedPathImpl(Device.first(), Object("Hosts."))
val DNS: ResolvedPath = ResolvedPathImpl(Device.first(), Object("DNS."))
val NAT: ResolvedPath = ResolvedPathImpl(Device.first(), Object("NAT."))
val PCP: ResolvedPath = ResolvedPathImpl(Device.first(), Object("PCP."))
val DHCPv4: ResolvedPath = ResolvedPathImpl(Device.first(), Object("DHCPv4."))
val DHCPv6: ResolvedPath = ResolvedPathImpl(Device.first(), Object("DHCPv6."))
val IEEE8021x: ResolvedPath = ResolvedPathImpl(Device.first(), Object("IEEE8021x."))
val Users: ResolvedPath = ResolvedPathImpl(Device.first(), Object("Users."))
val SmartCardReaders: ResolvedPath = ResolvedPathImpl(Device.first(), Object("SmartCardReaders."))
val UPnP: ResolvedPath = ResolvedPathImpl(Device.first(), Object("UPnP."))
val DLNA: ResolvedPath = ResolvedPathImpl(Device.first(), Object("DLNA."))
val Firewall: ResolvedPath = ResolvedPathImpl(Device.first(), Object("Firewall."))
val PeriodicStatistics: ResolvedPath =
    ResolvedPathImpl(Device.first(), Object("PeriodicStatistics."))
val FaultMgmt: ResolvedPath = ResolvedPathImpl(Device.first(), Object("FaultMgmt."))
val Security: ResolvedPath = ResolvedPathImpl(Device.first(), Object("Security."))
val FAP: ResolvedPath = ResolvedPathImpl(Device.first(), Object("FAP."))
val BulkData: ResolvedPath = ResolvedPathImpl(Device.first(), Object("BulkData."))
val SoftwareModules: ResolvedPath = ResolvedPathImpl(Device.first(), Object("SoftwareModules."))
val XMPP: ResolvedPath = ResolvedPathImpl(Device.first(), Object("XMPP."))
val IEEE1905: ResolvedPath = ResolvedPathImpl(Device.first(), Object("IEEE1905."))
val MQTT: ResolvedPath = ResolvedPathImpl(Device.first(), Object("MQTT."))
val DynamicDNS: ResolvedPath = ResolvedPathImpl(Device.first(), Object("DynamicDNS."))
val LEDs: ResolvedPath = ResolvedPathImpl(Device.first(), Object("LEDs."))
val BASAPM: ResolvedPath = ResolvedPathImpl(Device.first(), Object("BASAPM."))
val LMAP: ResolvedPath = ResolvedPathImpl(Device.first(), Object("LMAP."))
val WWC: ResolvedPath = ResolvedPathImpl(Device.first(), Object("WWC."))
val PDU: ResolvedPath = ResolvedPathImpl(Device.first(), Object("PDU."))
val FWE: ResolvedPath = ResolvedPathImpl(Device.first(), Object("FWE."))
val Logical: ResolvedPath = ResolvedPathImpl(Device.first(), Object("Logical."))
val XPON: ResolvedPath = ResolvedPathImpl(Device.first(), Object("XPON."))
val SSH: ResolvedPath = ResolvedPathImpl(Device.first(), Object("SSH."))
val UnixDomainSockets: ResolvedPath = ResolvedPathImpl(Device.first(), Object("UnixDomainSockets."))
val USPServices: ResolvedPath = ResolvedPathImpl(Device.first(), Object("USPServices."))
val LocalAgent: ResolvedPath = ResolvedPathImpl(Device.first(), Object("LocalAgent."))
val Standby: ResolvedPath = ResolvedPathImpl(Device.first(), Object("Standby."))
val CWMPManagementServer: ResolvedPath =
    ResolvedPathImpl(Device.first(), Object("CWMPManagementServer."))
val STOMP: ResolvedPath = ResolvedPathImpl(Device.first(), Object("STOMP."))
val GatewayInfo: ResolvedPath = ResolvedPathImpl(Device.first(), Object("GatewayInfo."))