[versions]
usp = "0.1.0"

agp = "8.2.2"
kotlin = "1.9.23"
kotlinx-coroutines = "1.8.0"
kotlinx-serialization = "1.6.0"
wire = "4.9.3"
okio = "3.9.0"
moshi = "1.14.0"
ktor = "2.3.8"
kmqtt = "0.4.6"
mockery = "1.9.23-1.6.1" # First part of version name MUST be the Kotlin version!
kover = "0.8.0"
slf4j = "2.0.13"         # Used only in cli subproject

# Android specifics:
minSdk = "24"
compileSdk = "34"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-datetime = "org.jetbrains.kotlinx:kotlinx-datetime:0.5.0"
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json-okio = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json-okio", version.ref = "kotlinx-serialization" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-websockets = { module = "io.ktor:ktor-client-websockets", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }
clikt = "com.github.ajalt.clikt:clikt:4.3.0"
wire-runtime = { module = "com.squareup.wire:wire-runtime", version.ref = "wire" }
wire-moshi = { module = "com.squareup.wire:wire-moshi-adapter", version.ref = "wire" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
kermit = "co.touchlab:kermit:2.0.2"
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
okio-fakefilesystem = { module = "com.squareup.okio:okio-fakefilesystem", version.ref = "okio" }
kmqtt-common = { module = "io.github.davidepianca98:kmqtt-common", version.ref = "kmqtt" }
kmqtt-client = { module = "io.github.davidepianca98:kmqtt-client", version.ref = "kmqtt" }
slj4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slj4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlinCocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
wire = { id = "com.squareup.wire", version.ref = "wire" }
org-jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
mockery = { id = "dev.mokkery", version.ref = "mockery" }
allOpen = { id = "org.jetbrains.kotlin.plugin.allopen", version.ref = "kotlin" } # Used to mock final classes
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }