package de.telekom.usp

import kotlinx.coroutines.flow.SharedFlow
import okio.ByteString

/**
 * Abstraction for the message transfer protocol.
 */
interface EndpointConnection {

    /**
     * A shored flow of the events generated by this.
     */
    val events: SharedFlow<EndpointConnectionEvent>

    /**
     * Queues the specified bytes for sending with this endpoint connection
     */
    suspend fun send(bytes: ByteString)

    /**
     * Tries to establish a connection to the remote endpoint of this. Calling this method on a
     * connected instance must have no effects
     *
     * @see events
     */
    suspend fun connect()

    /**
     * Disconnects this connection from its endpoint. Calling this method on a disconnected instance
     * of this, must have no effect
     *
     * @see events
     */
    suspend fun disconnect()
}