/*
 * SPDX-FileCopyrightText: 2026 Deutsche Telekom AG
 *
 * SPDX-License-Identifier: Apache-2.0
 */

package de.telekom.usp.mtp

import kotlinx.coroutines.flow.SharedFlow
import okio.ByteString

/**
 * Abstraction for the message transfer protocol. Allows sending and receiving of byte strings
 * (which actually represent USP records, hence this interface should actually be called
 * RecordTransfer, but as the USP specification uses the term message transfer, we adopt it here
 * as well).
 */
interface MessageTransfer {

    /**
     * A shored flow of the events generated by this.
     */
    val events: SharedFlow<MessageTransferEvent>

    /**
     * Queues the specified bytes for sending with this endpoint connection
     */
    suspend fun send(bytes: ByteString)

    /**
     * Tries to establish a connection to the remote endpoint of this. Calling this method on a
     * connected instance must have no effects
     *
     * @see events
     */
    suspend fun connect()

    /**
     * Disconnects this connection from its endpoint. Calling this method on a disconnected instance
     * of this, must have no effect
     *
     * @see events
     */
    suspend fun disconnect()
}